### PR TITLE
Refrain from setting 200 OK on cached responses

### LINKED ISSUE #74: Changing status code of cached responses
After a while dealing with a really weird bug in our infra in which some services apparently returned a 200 response with an error body (which actually looked empty after parsing to our successful response types), I finally managed to reproduce it consistently and upon further investigation I found this code that replaces the status code of cached responses before returning them.

As I don't know why this was originally there (and it seems a pretty old change), I preferred not to send a PR right away and leave for someone with more context in the code to investigate. Couldn't find any RFCs specifying that non-OK responses should not be cached, but [this document](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#Targets_of_caching_operations) from Mozilla does imply even error responses are valid for caching (which was our case).

Would be really glad to see this fixed :)

https://github.com/gregjones/httpcache/blob/787624de3eb7bd915c329cba748687a3b22666a6/httpcache.go#L193

### PR DESCRIPTION
**Pull request by gregjones**
In cases where responses were re-used, due to
validated 304 responses and requests using stale-if-error,
the cached responses had their status replaced by a 200,
which isn't correct.

Fixes #74

### CODE REVIEW

File: httpcache_test.go [hunk 1]
```diff
@@ -1355,6 +1392,54 @@ func TestStaleIfErrorResponseLifetime(t *testing.T) {
 	}
 }
 
+func TestStaleIfErrorKeepsStatus(t *testing.T) {
```
Comment (shurcooL) [inline httpcache_test.go]: What is the difference in what this test is testing compared to `TestCachedErrorsKeepStatus`?

Comment (gregjones) [reply httpcache_test.go]: The other is for the case when a non-200 status is returned because it had etag/last-modified and it was validated. This one is for the case where we use a stale cached response because the request errors and the request had stale-if-error set.

Having written that, I see the test names (at least TestCachedErrorsKeepStatus) aren't so clear ... if you have suggestions they're welcome, or I'll think some more about it :)

Comment (shurcooL) [reply httpcache_test.go]: You could keep names as is, but add a comment documenting what kind of behavior is being tested. I admit, it's quite hard to deduct from looking at the test code what it intends to test.

**Comment by victorges** [comment]
Thanks for this! The change to `httpcache.go` is exactly the same I did on my fork to enable usage of the lib in our internal infrastructure, and it's been working fine since. Will switch back to the main lib in our services once this gets merged.

**Comment by shurcooL** [comment]
@victorges Thanks for the ping, I forgot about this PR. Also thanks for confirming that this same change fixes the issue for you, that helps inspire confidence.

Ping @gregjones. It seems what we last discussed was adding some documentation/comments to the test, to better explain what is being tested, so that we can then be sure the what the test is checking is correct behavior (it's really hard to tell if that's the case now).

I'll look at the implementation change and think more about it, but it looks reasonable so far. I'll also test it locally.

**Comment by shurcooL** [comment]
Friendly ping @gregjones (see comment above).

I've been testing this the last 2 weeks, haven't spotted any issues.

**Comment by gregjones** [comment]
Thank you for reminding me. I will look at this tomorrow

**Comment by gregjones** [comment]
I've added comments that explicitly call out that these were fixes for previous incorrect behaviour, I think that makes it clearer?

File: httpcache_test.go [hunk 2]
```diff
@@ -885,6 +885,9 @@ func TestUpdateFields(t *testing.T) {
 }
 
 func TestCachedErrorsKeepStatus(t *testing.T) {
+	// tests fix for https://github.com/gregjones/httpcache/issues/74
+	// previously, after validating a cached response, its StatusCode
+	// was incorrectly being replaced
```
Comment (shurcooL) [inline httpcache_test.go]: Minor, but I'd suggest moving the comment out to be on top of the entire test. It describes what the entire test does. E.g., compare with:

https://github.com/gregjones/httpcache/blob/cdafe69ab9c9f0346f6345a6c475e0c170f35dbb/httpcache_test.go#L173-L175

https://github.com/gregjones/httpcache/blob/cdafe69ab9c9f0346f6345a6c475e0c170f35dbb/httpcache_test.go#L1449-L1454

Also, I'd suggest using proper sentences that start with capital letters with periods at end. It makes it harder to read the text without periods. At first, I thought it was one sentence and felt confused. After, I realized that there are 2 sentences here, and the second sentence begins with "Previously, ...".

File: httpcache_test.go [hunk 3]
```diff
@@ -873,6 +884,35 @@ func TestUpdateFields(t *testing.T) {
 	}
 }
 
+// This tests the fix for https://github.com/gregjones/httpcache/issues/74.
+// Previously, after validating a cached response, its StatusCode
+// was incorrectly being replaced
```
Comment (shurcooL) [inline httpcache_test.go]: Minor, the period at end of sentence after "replaced" is missing here.

File: httpcache_test.go [hunk 4]
```diff
@@ -1355,6 +1395,57 @@ func TestStaleIfErrorResponseLifetime(t *testing.T) {
 	}
 }
 
+// This tests the fix for https://github.com/gregjones/httpcache/issues/74.
+// Previously, after a stale response was used after encountering an error,
+// its StatusCode was being incorrectly replaced.
```
Comment (shurcooL) [inline httpcache_test.go]: It's good here.
